/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nncryzbssbuhnlvqnjfc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uY3J5emJzc2J1aG5sdnFuamZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMjU4MDksImV4cCI6MjA4MzkwMTgwOX0.zmwBlhH-EtqnSogIwdnGJjwmie7TEY0--MM66-7JkWs"